This is not dict, the exception should be thrown.